# -*- coding: utf-8 -*-
"""Code_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WWCBefwWx9s9bvXD0z-5GQIgG_g5sgdq
"""

# Verificar GPU
!nvidia-smi


# Montar Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Instalar Ultralytics (YOLOv8)
!pip install ultralytics


# Verificar instalación
import ultralytics
print(f"Ultralytics version: {ultralytics.__version__}")

import os
import zipfile
import shutil
import yaml
from collections import Counter

# ============================================================================
# CONFIGURACIÓN DE RUTAS
# ============================================================================

DATA_DIR = "/content/drive/MyDrive/Data"
UNIFIED_DATASET_DIR = "/content/unified_dataset_multiclass_fixed"
TEMP_EXTRACT_DIR = "/content/temp_extraction_fixed"

print("🎯 CONFIGURACIÓN PARA UNIFICACIÓN MULTICLASE - VERSIÓN CORREGIDA:")
print(f"📁 Carpeta Data: {DATA_DIR}")
print(f"📁 Dataset unificado: {UNIFIED_DATASET_DIR}")

# Crear directorios
os.makedirs(UNIFIED_DATASET_DIR, exist_ok=True)
os.makedirs(TEMP_EXTRACT_DIR, exist_ok=True)

for split in ['train', 'valid', 'test']:
    for tipo in ['images', 'labels']:
        os.makedirs(os.path.join(UNIFIED_DATASET_DIR, split, tipo), exist_ok=True)

# ============================================================================
# FUNCIÓN MEJORADA PARA BUSCAR Y LEER DATA.YAML
# ============================================================================

def encontrar_y_leer_data_yaml(directorio):
    """Busca recursivamente el archivo data.yaml y lo lee"""
    for root, dirs, files in os.walk(directorio):
        if 'data.yaml' in files:
            data_yaml_path = os.path.join(root, 'data.yaml')
            try:
                with open(data_yaml_path, 'r') as f:
                    data_yaml = yaml.safe_load(f)
                return data_yaml, data_yaml_path
            except Exception as e:
                print(f"      ❌ Error leyendo data.yaml: {e}")
                return None, None
    return None, None

# ============================================================================
# PASO 1: ANALIZAR TODOS LOS DATASETS
# ============================================================================

def analizar_clases_datasets_mejorado():
    """Analiza todos los datasets con mejor manejo de errores"""
    print("\n🔍 ANALIZANDO CLASES EN TODOS LOS DATASETS...")

    if not os.path.exists(DATA_DIR):
        print(f"❌ La carpeta {DATA_DIR} no existe")
        return []

    todos_los_archivos_zip = [f for f in os.listdir(DATA_DIR) if f.endswith('.zip')]
    print(f"📦 Encontrados {len(todos_los_archivos_zip)} archivos ZIP: {todos_los_archivos_zip}")

    datasets_info = []

    for zip_file in todos_los_archivos_zip:
        zip_path = os.path.join(DATA_DIR, zip_file)
        nombre_limpio = zip_file.replace(' ', '_').replace('-', '_').replace('.zip', '')
        extract_path = os.path.join(TEMP_EXTRACT_DIR, nombre_limpio)

        print(f"\n   🔄 Procesando: {zip_file}")
        print(f"      📁 Extrayendo en: {extract_path}")

        try:
            with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                zip_test = zip_ref.testzip()
                if zip_test is not None:
                    print(f"      ❌ ZIP corrupto: {zip_test}")
                    continue
                zip_ref.extractall(extract_path)
                print(f"      ✅ Extraído correctamente")

            data_yaml, data_yaml_path = encontrar_y_leer_data_yaml(extract_path)

            if data_yaml is None:
                print(f"      ❌ No se pudo encontrar o leer data.yaml")
                continue

            print(f"      ✅ data.yaml encontrado en: {data_yaml_path}")

            clases = data_yaml.get('names', [])
            nc = data_yaml.get('nc', 0)

            counts = {}
            for split in ['train', 'valid', 'test']:
                images_count = 0
                for root, dirs, files in os.walk(extract_path):
                    if split in root.lower() and 'images' in root.lower():
                        images_count = len([f for f in files if f.lower().endswith(('.jpg', '.jpeg', '.png'))])
                        if images_count > 0:
                            break
                    elif os.path.basename(root) == split:
                        images_dir = os.path.join(root, 'images')
                        if os.path.exists(images_dir):
                            images_count = len([f for f in os.listdir(images_dir) if f.lower().endswith(('.jpg', '.jpeg', '.png'))])
                            break

                counts[split] = images_count

            datasets_info.append({
                'nombre': nombre_limpio,
                'clases': clases,
                'nc': nc,
                'counts': counts,
                'ruta': extract_path,
                'data_yaml': data_yaml
            })

            print(f"      ✅ {nombre_limpio}: {nc} clases → {clases}")
            print(f"      📊 Imágenes: train={counts['train']}, valid={counts['valid']}, test={counts['test']}")

        except zipfile.BadZipFile:
            print(f"      ❌ ERROR: Archivo ZIP corrupto - {zip_file}")
        except Exception as e:
            print(f"      ❌ ERROR inesperado procesando {zip_file}: {str(e)}")

    return datasets_info

# Analizar todos los datasets
datasets_info = analizar_clases_datasets_mejorado()

if not datasets_info:
    print("❌ No se pudieron analizar los datasets")
    exit()

print(f"\n✅ Datasets analizados exitosamente: {len(datasets_info)}")

# ============================================================================
# PASO 2: CREAR LISTA MAESTRA DE TODAS LAS CLASES
# ============================================================================

print(f"\n🎯 CREANDO LISTA MAESTRA DE CLASES...")

todas_las_clases = []
for dataset in datasets_info:
    todas_las_clases.extend(dataset['clases'])

contador_clases = Counter(todas_las_clases)
clases_unicas = list(contador_clases.keys())

print(f"📊 ESTADÍSTICAS DE CLASES:")
for clase, count in contador_clases.items():
    print(f"   🏷️  {clase}: aparece en {count} datasets")

print(f"\n📋 LISTA MAESTRA DE CLASES ({len(clases_unicas)} clases): {clases_unicas}")

mapeo_maestro = {clase: idx for idx, clase in enumerate(clases_unicas)}
print(f"🔢 MAPEO MAESTRO: {mapeo_maestro}")

# ============================================================================
# FUNCIÓN MEJORADA PARA ENCONTRAR CARPETAS
# ============================================================================

def encontrar_carpetas_split(ruta_base, split):
    """Encuentra carpetas de imágenes y etiquetas para un split específico"""
    posibles_images = []
    posibles_labels = []

    # Estrategia 1: Estructura estándar YOLO
    std_images = os.path.join(ruta_base, split, 'images')
    std_labels = os.path.join(ruta_base, split, 'labels')

    if os.path.exists(std_images) and os.listdir(std_images):
        posibles_images.append(std_images)
    if os.path.exists(std_labels) and os.listdir(std_labels):
        posibles_labels.append(std_labels)

    # Estrategia 2: Búsqueda recursiva
    for root, dirs, files in os.walk(ruta_base):
        # Solo considerar si estamos en el nivel del split
        if split.lower() in root.lower():
            # Buscar carpeta de imágenes
            if 'images' in root.lower() and any(f.lower().endswith(('.jpg', '.jpeg', '.png')) for f in files):
                if root not in posibles_images:
                    posibles_images.append(root)

            # Buscar carpeta de etiquetas
            if 'labels' in root.lower() and any(f.endswith('.txt') for f in files):
                if root not in posibles_labels:
                    posibles_labels.append(root)

    # Priorizar rutas que tengan "images" en el nombre
    images_prioritarias = [r for r in posibles_images if 'images' in r.lower()]
    labels_prioritarias = [r for r in posibles_labels if 'labels' in r.lower()]

    # Si hay rutas prioritarias, usarlas; si no, usar las primeras encontradas
    origen_images = images_prioritarias[0] if images_prioritarias else (posibles_images[0] if posibles_images else None)
    origen_labels = labels_prioritarias[0] if labels_prioritarias else (posibles_labels[0] if posibles_labels else None)

    return origen_images, origen_labels

# ============================================================================
# PASO 3: PROCESAR DATASETS CON LÓGICA CORREGIDA
# ============================================================================

def procesar_dataset_corregido(dataset_info, contador_global):
    """Versión corregida para copiar imágenes y etiquetas"""
    nombre = dataset_info['nombre']
    ruta = dataset_info['ruta']
    clases_originales = dataset_info['clases']

    print(f"\n🔄 PROCESANDO: {nombre}")
    print(f"   📁 Ruta del dataset: {ruta}")

    # Crear mapeo específico para este dataset
    mapeo_dataset = {}
    for idx_original, clase_original in enumerate(clases_originales):
        mapeo_dataset[idx_original] = mapeo_maestro[clase_original]

    print(f"   🔄 Mapeo: {mapeo_dataset}")

    total_imagenes_procesadas = 0
    total_etiquetas_procesadas = 0

    for split in ['train', 'valid', 'test']:
        print(f"\n   🔍 BUSCANDO SPLIT: {split}")

        origen_images, origen_labels = encontrar_carpetas_split(ruta, split)

        print(f"      📂 Ruta imágenes: {origen_images}")
        print(f"      📂 Ruta etiquetas: {origen_labels}")

        if not origen_images:
            print(f"      ⚠️  No se encontraron imágenes para {split}")
            continue

        destino_images = os.path.join(UNIFIED_DATASET_DIR, split, 'images')
        destino_labels = os.path.join(UNIFIED_DATASET_DIR, split, 'labels')

        # COPIAR IMÁGENES
        try:
            if origen_images and os.path.exists(origen_images):
                imagenes = [f for f in os.listdir(origen_images) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
                print(f"      🖼️  Encontradas {len(imagenes)} imágenes")

                for archivo in imagenes:
                    nuevo_nombre = f"ds{contador_global:02d}_{split}_{archivo}"
                    shutil.copy2(
                        os.path.join(origen_images, archivo),
                        os.path.join(destino_images, nuevo_nombre)
                    )
                    total_imagenes_procesadas += 1

                print(f"      ✅ Copiadas {len(imagenes)} imágenes")
            else:
                print(f"      ❌ No se pudo acceder a la carpeta de imágenes: {origen_images}")

        except Exception as e:
            print(f"      ❌ Error copiando imágenes: {e}")

        # COPIAR Y CONVERTIR ETIQUETAS
        if origen_labels and os.path.exists(origen_labels):
            try:
                etiquetas = [f for f in os.listdir(origen_labels) if f.endswith('.txt')]
                print(f"      📝 Encontradas {len(etiquetas)} etiquetas")

                for archivo in etiquetas:
                    nuevo_nombre = f"ds{contador_global:02d}_{split}_{archivo}"
                    origen_etiqueta = os.path.join(origen_labels, archivo)
                    destino_etiqueta = os.path.join(destino_labels, nuevo_nombre)

                    try:
                        with open(origen_etiqueta, 'r') as f:
                            lineas_originales = f.readlines()

                        lineas_convertidas = []
                        for linea in lineas_originales:
                            partes = linea.strip().split()
                            if len(partes) >= 5:
                                clase_original_idx = int(partes[0])
                                clase_maestra_idx = mapeo_dataset[clase_original_idx]
                                partes[0] = str(clase_maestra_idx)
                                lineas_convertidas.append(' '.join(partes) + '\n')

                        with open(destino_etiqueta, 'w') as f:
                            f.writelines(lineas_convertidas)

                        total_etiquetas_procesadas += 1

                    except Exception as e:
                        print(f"      ❌ Error procesando etiqueta {archivo}: {e}")

                print(f"      ✅ Procesadas {len(etiquetas)} etiquetas")

            except Exception as e:
                print(f"      ❌ Error general con etiquetas: {e}")
        else:
            print(f"      ⚠️  No se encontraron etiquetas para {split}")

    print(f"   ✅ {nombre} procesado: {total_imagenes_procesadas} imágenes, {total_etiquetas_procesadas} etiquetas")
    return total_imagenes_procesadas, total_etiquetas_procesadas

print(f"\n🚀 INICIANDO UNIFICACIÓN MANTENIENDO {len(clases_unicas)} CLASES...")

# Procesar todos los datasets
total_imagenes_unificadas = 0
total_etiquetas_unificadas = 0

for i, dataset in enumerate(datasets_info):
    imagenes, etiquetas = procesar_dataset_corregido(dataset, i)
    total_imagenes_unificadas += imagenes
    total_etiquetas_unificadas += etiquetas

# ============================================================================
# PASO 4: CREAR DATA.YAML
# ============================================================================

print(f"\n📄 CREANDO DATA.YAML CON {len(clases_unicas)} CLASES...")

data_yaml_multiclass = f"""path: {UNIFIED_DATASET_DIR}
train: train/images
val: valid/images
test: test/images

nc: {len(clases_unicas)}
names: {clases_unicas}
"""

data_yaml_path = os.path.join(UNIFIED_DATASET_DIR, 'data.yaml')
with open(data_yaml_path, 'w') as f:
    f.write(data_yaml_multiclass)

print(f"✅ data.yaml creado con {len(clases_unicas)} clases")

# ============================================================================
# PASO 5: VERIFICACIÓN FINAL
# ============================================================================

print(f"\n📊 ESTADÍSTICAS FINALES DEL DATASET MULTICLASE:")
print("=" * 60)

# Contar archivos en el dataset unificado
for split in ['train', 'valid', 'test']:
    images_dir = os.path.join(UNIFIED_DATASET_DIR, split, 'images')
    labels_dir = os.path.join(UNIFIED_DATASET_DIR, split, 'labels')

    imagenes_count = len([f for f in os.listdir(images_dir)]) if os.path.exists(images_dir) else 0
    etiquetas_count = len([f for f in os.listdir(labels_dir)]) if os.path.exists(labels_dir) else 0

    print(f"📂 {split.upper()}:")
    print(f"   🖼️  Imágenes: {imagenes_count}")
    print(f"   📝 Etiquetas: {etiquetas_count}")

print(f"\n🎯 TOTALES UNIFICADOS:")
print(f"   🖼️  Imágenes: {total_imagenes_unificadas}")
print(f"   📝 Etiquetas: {total_etiquetas_unificadas}")
print(f"   🏷️  Número de clases: {len(clases_unicas)}")
print(f"   📊 Datasets combinados: {len(datasets_info)}")

# ============================================================================
# LIMPIEZA
# ============================================================================

print(f"\n🧹 LIMPIANDO TEMPORALES...")
if os.path.exists(TEMP_EXTRACT_DIR):
    shutil.rmtree(TEMP_EXTRACT_DIR)

print(f"\n🎉 DATASET MULTICLASE CREADO EXITOSAMENTE!")
print(f"📍 Ruta: {UNIFIED_DATASET_DIR}")

"""# **QUIERO QUE LA RECOMENDACION QUE SE HAGA SE PONGA EN UNA VARIABLE Y ASI SE PUEDA UTILIZAR PARA EL SIGUIENTE CODIGO**"""

# ============================================================================
# PARTE 1: ANÁLISIS COMPLETO DEL MODELO
# ============================================================================

import os
import glob
import torch
from ultralytics import YOLO
import yaml

print("🎯 PARTE 1: ANÁLISIS COMPLETO DEL MODELO")
print("=" * 60)

# Configuración de rutas
CARPETA_MODELOS = '/content/drive/MyDrive/Modelos'
DATA_PATH = '/content/unified_dataset_multiclass_fixed/data.yaml'

def analizar_modelo_completamente():
    """Análisis exhaustivo del modelo más reciente"""

    # 1. BUSCAR MODELOS
    print("🔍 BUSCANDO MODELOS...")
    if not os.path.exists(CARPETA_MODELOS):
        print(f"❌ La carpeta {CARPETA_MODELOS} no existe")
        return None

    patron = os.path.join(CARPETA_MODELOS, "best*.pt")
    modelos = glob.glob(patron)

    if not modelos:
        print("❌ No se encontraron modelos best*.pt")
        patron_recursivo = os.path.join(CARPETA_MODELOS, "**", "best*.pt")
        modelos = glob.glob(patron_recursivo, recursive=True)

    if not modelos:
        print("❌ No se encontraron modelos en ninguna subcarpeta")
        return None

    # Ordenar por número en el nombre
    def extraer_numero(ruta):
        nombre = os.path.basename(ruta)
        try:
            import re
            numeros = re.findall(r'best_?(\d+)\.pt', nombre)
            return int(numeros[0]) if numeros else 0
        except:
            return 0

    modelos_ordenados = sorted(modelos, key=extraer_numero, reverse=True)

    print(f"✅ Encontrados {len(modelos_ordenados)} modelos:")
    for i, modelo in enumerate(modelos_ordenados[:5]):
        num = extraer_numero(modelo)
        print(f"   {i+1}. {os.path.basename(modelo)} (número: {num})")

    modelo_seleccionado = modelos_ordenados[0]
    print(f"\n🎯 MODELO SELECCIONADO PARA ANÁLISIS: {modelo_seleccionado}")

    # 2. ANÁLISIS DETALLADO DEL MODELO
    print(f"\n🔬 ANALIZANDO MODELO...")
    try:
        model = YOLO(modelo_seleccionado)

        print("📊 INFORMACIÓN BÁSICA:")
        print(f"   📁 Ruta: {modelo_seleccionado}")
        print(f"   🏷️  Tipo: {type(model).__name__}")

        # Información de arquitectura
        if hasattr(model, 'model'):
            modelo_info = model.model
            print(f"   🏗️  Arquitectura: {type(modelo_info).__name__}")

            # Número de clases
            if hasattr(modelo_info, 'nc'):
                nc = modelo_info.nc
                print(f"   🎯 Número de clases: {nc}")
            else:
                nc = None

            # Parámetros
            if hasattr(modelo_info, 'parameters'):
                total_params = sum(p.numel() for p in modelo_info.parameters())
                print(f"   🔢 Parámetros totales: {total_params:,}")
                print(f"   💾 Tamaño estimado: {total_params * 4 / 1024**2:.1f} MB (FP32)")

        # Nombres de clases
        if hasattr(model, 'names') and model.names:
            print(f"   📝 Clases del modelo: {model.names}")
            print(f"   🏷️  Total de clases: {len(model.names)}")
        else:
            print(f"   ⚠️  No se pudieron obtener los nombres de clases")

        # Metadata
        if hasattr(model, 'metadata'):
            print(f"   📋 Metadata: {model.metadata}")

        # Información del checkpoint
        if hasattr(model, 'ckpt_path'):
            print(f"   💾 Checkpoint path: {model.ckpt_path}")

        return model, nc, modelo_seleccionado

    except Exception as e:
        print(f"❌ Error analizando el modelo: {e}")
        return None, None, None

def analizar_dataset():
    """Analiza el dataset unificado"""
    print(f"\n📊 ANALIZANDO DATASET...")

    try:
        with open(DATA_PATH, 'r') as f:
            data_config = yaml.safe_load(f)

        nc_dataset = data_config.get('nc', 0)
        nombres_clases = data_config.get('names', [])

        print(f"📁 Dataset: {DATA_PATH}")
        print(f"🎯 Número de clases: {nc_dataset}")
        print(f"📝 Clases: {nombres_clases}")

        # Estadísticas de imágenes
        base_path = data_config.get('path', '')
        if os.path.exists(base_path):
            for split in ['train', 'valid', 'test']:
                split_path = os.path.join(base_path, split, 'images')
                if os.path.exists(split_path):
                    num_imagenes = len([f for f in os.listdir(split_path) if f.endswith(('.jpg', '.png'))])
                    print(f"   📂 {split}: {num_imagenes} imágenes")

        return nc_dataset, nombres_clases

    except Exception as e:
        print(f"❌ Error analizando dataset: {e}")
        return None, None

# Ejecutar análisis
modelo, nc_modelo, ruta_modelo = analizar_modelo_completamente()
nc_dataset, nombres_dataset = analizar_dataset()

# 3. COMPARACIÓN Y RECOMENDACIONES
print(f"\n🎯 COMPARACIÓN Y RECOMENDACIONES")
print("=" * 60)

if nc_modelo is not None and nc_dataset is not None:
    print(f"🔍 COMPARACIÓN DE CLASES:")
    print(f"   🏷️  Modelo actual: {nc_modelo} clases")
    print(f"   🏷️  Dataset objetivo: {nc_dataset} clases")

    if nc_modelo == nc_dataset:
        print(f"✅ COMPATIBILIDAD PERFECTA")
        print(f"💡 RECOMENDACIÓN: Fine-tuning directo")

    elif nc_modelo > nc_dataset:
        print(f"⚠️  MODELO TIENE MÁS CLASES")
        print(f"💡 RECOMENDACIÓN: Fine-tuning conservador (reutilizar características)")

    else:
        print(f"🔄 MODELO TIENE MENOS CLASES")
        print(f"💡 RECOMENDACIÓN: Fine-tuning adaptativo (aprender nuevas clases)")

    # Análisis de rendimiento esperado
    print(f"\n📈 EXPECTATIVAS DE RENDIMIENTO:")
    total_imagenes = sum([len([f for f in os.listdir(os.path.join('/content/unified_dataset_multiclass_fixed', split, 'images'))
                              if f.endswith(('.jpg', '.png'))])
                         for split in ['train', 'valid', 'test']
                         if os.path.exists(os.path.join('/content/unified_dataset_multiclass_fixed', split, 'images'))])

    print(f"   📊 Dataset size: {total_imagenes} imágenes")
    print(f"   ⏱️  Épocas recomendadas: {30 if nc_modelo == nc_dataset else 25 if nc_modelo > nc_dataset else 35}")
    print(f"   🔽 Learning rate recomendado: {0.001 if nc_modelo == nc_dataset else 0.0005 if nc_modelo > nc_dataset else 0.002}")

else:
    print("❌ No se pudo completar el análisis de compatibilidad")

# 4. RESUMEN FINAL DEL ANÁLISIS
print(f"\n📋 RESUMEN DEL ANÁLISIS")
print("=" * 60)

if modelo is not None:
    print(f"✅ MODELO ENCONTRADO Y ANALIZADO:")
    print(f"   📁 {os.path.basename(ruta_modelo)}")
    print(f"   🏷️  Clases: {nc_modelo}")
    print(f"   🎯 Estado: Listo para fine-tuning")
else:
    print(f"❌ No se pudo cargar un modelo válido")
    print(f"💡 Se usará YOLOv8s-seg base")

print(f"\n🎉 ANÁLISIS COMPLETADO!")
print(f"💾 Modelo: {ruta_modelo if modelo else 'YOLOv8s-seg (base)'}")
print(f"📊 Clases modelo: {nc_modelo}")
print(f"📊 Clases dataset: {nc_dataset}")

"""# **QUIERO COGER LOS PARÁMETROS DEL ANTERIOR CODIGO Y ASI PODER UTILIZARLO**

# **QUIERO QUE TODOS LOS RESULTADOS SE COPIEN BIEN EN EL DRIVE, ACTUALMENTE SE QUEDAN EN EL CONTENT/ AUNQUE SI QUE DEJA EL MODELO EN SU CARPETA CORRESPONDIENTE**
"""

import os
import yaml
import shutil
from ultralytics import YOLO
import torch

# ============================================================================
# CONFIGURACIÓN PARA INSTANCE SEGMENTATION
# ============================================================================

print("🎯 CONFIGURACIÓN PARA INSTANCE SEGMENTATION")
print("============================================================\n")

# Rutas
TFG_CODIGO_DIR = "/content/TFG_Codigo"
MODELOS_DIR = "/content/drive/MyDrive/Modelos"
MODELO_PRETRAINED = "/content/drive/MyDrive/Modelos/best_00.pt"  # Tu modelo actual de segmentation
DATASET_PATH = "/content/unified_dataset_multiclass_fixed/data.yaml"

# Crear directorios
os.makedirs(TFG_CODIGO_DIR, exist_ok=True)
os.makedirs(MODELOS_DIR, exist_ok=True)

# ============================================================================
# FUNCIÓN PARA DETERMINAR EL SIGUIENTE NÚMERO DE MODELO
# ============================================================================

def obtener_siguiente_modelo():
    """Encuentra el siguiente número disponible para Modelo_XX"""
    modelos_existentes = []
    for item in os.listdir(TFG_CODIGO_DIR):
        if item.startswith("Modelo_") and os.path.isdir(os.path.join(TFG_CODIGO_DIR, item)):
            try:
                num = int(item.replace("Modelo_", ""))
                modelos_existentes.append(num)
            except ValueError:
                continue

    bests_existentes = []
    for item in os.listdir(MODELOS_DIR):
        if item.startswith("best_") and item.endswith(".pt"):
            try:
                num = int(item.replace("best_", "").replace(".pt", ""))
                bests_existentes.append(num)
            except ValueError:
                continue

    max_tfg = max(modelos_existentes) if modelos_existentes else 0
    max_best = max(bests_existentes) if bests_existentes else 0
    siguiente_numero = max(max_tfg, max_best) + 1
    return siguiente_numero

NUMERO_MODELO = obtener_siguiente_modelo()
MODELO_ACTUAL_DIR = os.path.join(TFG_CODIGO_DIR, f"Modelo_{NUMERO_MODELO:02d}")
BEST_MODEL_NAME = f"best_{NUMERO_MODELO:02d}.pt"
BEST_MODEL_PATH = os.path.join(MODELOS_DIR, BEST_MODEL_NAME)

print("📋 CONFIGURACIÓN:")
print(f"   🔢 Modelo: Modelo_{NUMERO_MODELO:02d}")
print(f"   📂 Directorio: {MODELO_ACTUAL_DIR}")
print(f"   💾 Mejor modelo: {BEST_MODEL_PATH}")
print(f"   🎯 Tipo: Instance Segmentation")

# ============================================================================
# VERIFICACIÓN Y PREPARACIÓN
# ============================================================================

print(f"\n🔍 VERIFICANDO DATOS...")

# Verificar modelo preentrenado
if not os.path.exists(MODELO_PRETRAINED):
    print(f"❌ ERROR: No se encuentra el modelo {MODELO_PRETRAINED}")
    exit()
print(f"✅ Modelo preentrenado encontrado: {MODELO_PRETRAINED}")

# Verificar dataset
if not os.path.exists(DATASET_PATH):
    print(f"❌ ERROR: No se encuentra el dataset {DATASET_PATH}")
    exit()
print(f"✅ Dataset encontrado: {DATASET_PATH}")

# Leer configuración del dataset
with open(DATASET_PATH, 'r') as f:
    dataset_config = yaml.safe_load(f)

NUM_CLASES = dataset_config['nc']
CLASES = dataset_config['names']

print(f"✅ Clases: {NUM_CLASES}")
print(f"🏷️  Nombres: {CLASES}")

# Verificar estructura del dataset
print(f"\n📊 ESTADÍSTICAS DEL DATASET:")
for split in ['train', 'val', 'test']:
    split_path = dataset_config.get(split, '')
    if split_path:
        full_path = os.path.join(dataset_config['path'], split_path)
        if os.path.exists(full_path):
            num_images = len([f for f in os.listdir(full_path)
                            if f.lower().endswith(('.jpg', '.jpeg', '.png'))])
            num_labels = len([f for f in os.listdir(full_path.replace('images', 'labels'))
                            if f.endswith('.txt')]) if os.path.exists(full_path.replace('images', 'labels')) else 0
            print(f"   📂 {split.upper()}: {num_images} imágenes, {num_labels} etiquetas")
        else:
            print(f"   ⚠️  {split.upper()}: No encontrado")

# ============================================================================
# VERIFICACIÓN DEL MODELO DE SEGMENTATION
# ============================================================================

print(f"\n🔍 ANALIZANDO MODELO DE SEGMENTATION...")

try:
    modelo = YOLO(MODELO_PRETRAINED)
    print(f"✅ Modelo de segmentation cargado correctamente")
    print(f"📊 Tipo: {modelo.task}")
    print(f"🏗️  Arquitectura: {type(modelo.model).__name__}")
    print(f"🏷️  Número de clases: {modelo.model.nc}")

    # Verificar compatibilidad
    if modelo.model.nc == NUM_CLASES:
        print("✅ COMPATIBILIDAD PERFECTA - Mismo número de clases")
    else:
        print(f"⚠️  El modelo tiene {modelo.model.nc} clases, el dataset {NUM_CLASES}")
        print("💡 Se ajustará durante el entrenamiento")

except Exception as e:
    print(f"❌ Error cargando modelo: {e}")
    exit()

# ============================================================================
# CONFIGURACIÓN DE ENTRENAMIENTO PARA SEGMENTATION
# ============================================================================

print(f"\n⚙️  CONFIGURANDO ENTRENAMIENTO PARA INSTANCE SEGMENTATION...")

# Parámetros optimizados para segmentation
EPOCAS = 50  # Más épocas para segmentation
LEARNING_RATE = 0.001
BATCH_SIZE = 8 if torch.cuda.is_available() else 4  # Más pequeño por la complejidad
IMGSZ = 640

# Configuración específica para segmentation
config_entrenamiento = {
    'data': DATASET_PATH,
    'epochs': EPOCAS,
    'lr0': LEARNING_RATE,
    'lrf': 0.01,  # Learning rate final
    'batch': BATCH_SIZE,
    'imgsz': IMGSZ,
    'patience': 15,  # Más paciencia para segmentation
    'save': True,
    'save_period': 10,  # Guardar cada 10 épocas
    'cache': True,  # Cache para velocidad
    'device': 'cuda' if torch.cuda.is_available() else 'cpu',
    'workers': 4,  # Menos workers para segmentation
    'project': TFG_CODIGO_DIR,
    'name': f'Modelo_{NUMERO_MODELO:02d}',
    'exist_ok': False,
    'pretrained': True,  # Usar pesos preentrenados
    'optimizer': 'auto',
    'verbose': True,
    'amp': True,  # Mixed precision
    # Parámetros específicos de segmentation
    'overlap_mask': True,  # Permitir máscaras superpuestas
    'mask_ratio': 4,  # Resolución de máscaras (1/4 del tamaño de imagen)
    'box': 7.5,  # Peso para pérdida de bounding box
    'cls': 0.5,  # Peso para pérdida de clase
    'dfl': 1.5,  # Peso para pérdida de distribución focal
}

print("📋 PARÁMETROS DE SEGMENTATION:")
print(f"   🔄 Épocas: {EPOCAS}")
print(f"   📈 Learning rate: {LEARNING_RATE}")
print(f"   📦 Batch size: {BATCH_SIZE}")
print(f"   🖼️  Tamaño imagen: {IMGSZ}")
print(f"   🎭 Overlap mask: {config_entrenamiento['overlap_mask']}")
print(f"   📐 Mask ratio: {config_entrenamiento['mask_ratio']}")
print(f"   ⏳ Paciencia: {config_entrenamiento['patience']}")

# ============================================================================
# ENTRENAMIENTO
# ============================================================================

print(f"\n🚀 INICIANDO ENTRENAMIENTO DE INSTANCE SEGMENTATION...")
print("⏰ Este proceso puede tomar tiempo debido a la complejidad de segmentation...\n")

try:
    results = modelo.train(**config_entrenamiento)
    print("✅ ENTRENAMIENTO DE SEGMENTATION COMPLETADO!")

except Exception as e:
    print(f"❌ Error en entrenamiento: {e}")
    exit()

# ============================================================================
# GESTIÓN DE ARCHIVOS
# ============================================================================

print(f"\n💾 GESTIONANDO ARCHIVOS...")

# Copiar mejor modelo
best_model_train_path = os.path.join(MODELO_ACTUAL_DIR, 'weights', 'best.pt')
if os.path.exists(best_model_train_path):
    shutil.copy2(best_model_train_path, BEST_MODEL_PATH)
    print(f"✅ Mejor modelo copiado a: {BEST_MODEL_PATH}")
else:
    print(f"⚠️  No se encontró best.pt en: {best_model_train_path}")

    # Buscar alternativas
    last_model_path = os.path.join(MODELO_ACTUAL_DIR, 'weights', 'last.pt')
    if os.path.exists(last_model_path):
        shutil.copy2(last_model_path, BEST_MODEL_PATH)
        print(f"✅ Último modelo copiado a: {BEST_MODEL_PATH}")
    else:
        print("❌ No se pudo encontrar ningún modelo para copiar")

# ============================================================================
# EVALUACIÓN DETALLADA
# ============================================================================

print(f"\n📊 EVALUANDO MODELO DE SEGMENTATION...")

try:
    if os.path.exists(BEST_MODEL_PATH):
        modelo_final = YOLO(BEST_MODEL_PATH)
        metrics = modelo_final.val()

        print("✅ MÉTRICAS DE SEGMENTATION:")
        print(f"   📈 mAP50: {metrics.box.map50:.4f}")
        print(f"   📈 mAP50-95: {metrics.box.map:.4f}")
        print(f"   🎯 Precisión: {metrics.box.p:.4f}")
        print(f"   🔍 Recall: {metrics.box.r:.4f}")

        # Métricas específicas de segmentation
        if hasattr(metrics, 'seg') and metrics.seg is not None:
            print(f"   🎭 mAP50 seg: {metrics.seg.map50:.4f}")
            print(f"   🎭 mAP50-95 seg: {metrics.seg.map:.4f}")
        else:
            # Calcular métricas manualmente si es necesario
            print("   📝 Evaluando métricas de segmentation...")
            try:
                seg_metrics = modelo_final.val(split='test')
                if hasattr(seg_metrics, 'seg'):
                    print(f"   🎭 mAP50 seg: {seg_metrics.seg.map50:.4f}")
                    print(f"   🎭 mAP50-95 seg: {seg_metrics.seg.map:.4f}")
            except:
                print("   ⚠️  Métricas de segmentation no disponibles")

        # Guardar métricas detalladas
        metrics_file = os.path.join(MODELO_ACTUAL_DIR, f"metricas_segmentation_{NUMERO_MODELO:02d}.txt")
        with open(metrics_file, 'w') as f:
            f.write(f"METRICAS DE SEGMENTATION - Modelo_{NUMERO_MODELO:02d}\n")
            f.write("=" * 50 + "\n")
            f.write(f"mAP50: {metrics.box.map50:.4f}\n")
            f.write(f"mAP50-95: {metrics.box.map:.4f}\n")
            f.write(f"Precisión: {metrics.box.p:.4f}\n")
            f.write(f"Recall: {metrics.box.r:.4f}\n")
            if hasattr(metrics, 'seg') and metrics.seg is not None:
                f.write(f"mAP50 seg: {metrics.seg.map50:.4f}\n")
                f.write(f"mAP50-95 seg: {metrics.seg.map:.4f}\n")
            f.write(f"Épocas: {EPOCAS}\n")
            f.write(f"Learning rate: {LEARNING_RATE}\n")
            f.write(f"Batch size: {BATCH_SIZE}\n")
            f.write(f"Clases: {NUM_CLASES}\n")

        print(f"💾 Métricas guardadas en: {metrics_file}")

    else:
        print("⚠️  No se puede evaluar - modelo no encontrado")

except Exception as e:
    print(f"❌ Error en evaluación: {e}")

# ============================================================================
# PREDICCIÓN DE DEMOSTRACIÓN CON SEGMENTATION
# ============================================================================

print(f"\n🎯 DEMOSTRACIÓN DE SEGMENTATION...")

try:
    if os.path.exists(BEST_MODEL_PATH):
        modelo_final = YOLO(BEST_MODEL_PATH)

        # Buscar imagen de prueba
        test_images_dir = os.path.join(dataset_config['path'], 'test', 'images')
        if os.path.exists(test_images_dir) and os.listdir(test_images_dir):
            test_image = os.path.join(test_images_dir, os.listdir(test_images_dir)[0])

            print(f"🖼️  Realizando segmentación en: {os.path.basename(test_image)}")

            # Predicción con visualización de máscaras
            results = modelo_final.predict(
                test_image,
                save=True,
                imgsz=IMGSZ,
                conf=0.25,  # Confianza mínima
                iou=0.45,   # IoU para NMS
                show_labels=True,
                show_conf=True,
                project=MODELO_ACTUAL_DIR,
                name='demostracion_segmentation'
            )

            print(f"✅ Segmentación completada")
            print(f"📁 Resultados en: {os.path.join(MODELO_ACTUAL_DIR, 'demostracion_segmentation')}")

            # Mostrar estadísticas de la predicción
            for i, r in enumerate(results):
                print(f"   🖼️  Imagen {i+1}:")
                print(f"      🎭 Objetos detectados: {len(r.boxes)}")
                if r.masks is not None:
                    print(f"      🎭 Máscaras generadas: {len(r.masks)}")
                    # Contar instancias por clase
                    class_counts = {}
                    for box in r.boxes:
                        cls = int(box.cls[0])
                        class_name = modelo_final.names[cls]
                        class_counts[class_name] = class_counts.get(class_name, 0) + 1
                    print(f"      📊 Distribución: {class_counts}")
                else:
                    print(f"      ⚠️  No se generaron máscaras")

        else:
            print("⚠️  No hay imágenes de prueba para demostración")

    else:
        print("⚠️  No hay modelo para demostración")

except Exception as e:
    print(f"❌ Error en demostración: {e}")

# ============================================================================
# RESUMEN FINAL
# ============================================================================

print(f"\n🎉 ENTRENAMIENTO DE INSTANCE SEGMENTATION COMPLETADO!")
print("=" * 60)
print(f"🔢 MODELO: Modelo_{NUMERO_MODELO:02d}")
print(f"📁 DIRECTORIO: {MODELO_ACTUAL_DIR}")
print(f"💾 MEJOR MODELO: {BEST_MODEL_PATH}")
print(f"🔢 ÉPOCAS: {EPOCAS}")
print(f"📈 LEARNING RATE: {LEARNING_RATE}")
print(f"🏷️  CLASES: {NUM_CLASES}")
print(f"🎭 TIPO: Instance Segmentation")
print("=" * 60)

print(f"\n📂 ESTRUCTURA CREADA:")
print(f"   TFG_Codigo/Modelo_{NUMERO_MODELO:02d}/")
print(f"   ├── weights/")
print(f"   │   ├── best.pt")
print(f"   │   └── last.pt")
print(f"   ├── metricas_segmentation_{NUMERO_MODELO:02d}.txt")
print(f"   └── demostracion_segmentation/")
print(f"   Modelos/best_{NUMERO_MODELO:02d}.pt")

print(f"\n🚀 ¡MODELO DE SEGMENTATION Modelo_{NUMERO_MODELO:02d} LISTO!")

import os
import glob
import re
from ultralytics import YOLO
import cv2
import json
import numpy as np

# ============================================================================
# CONFIGURACIÓN DE RUTAS
# ============================================================================

print("🎯 CONFIGURACIÓN PARA ANÁLISIS DE VIDEOS CON SEGMENTATION Y ANOTACIONES")
print("=======================================================================\n")

# Rutas base
MODELOS_DIR = "/content/drive/MyDrive/Modelos"
VIDEOS_DIR = "/content/drive/MyDrive/Videos"
RESULTADOS_BASE = "/content/drive/MyDrive/Resultados"

# Verificar que existe la carpeta Resultados
if not os.path.exists(RESULTADOS_BASE):
    print(f"⚠️  La carpeta Resultados no existe, creándola...")
    os.makedirs(RESULTADOS_BASE)

print("📋 RUTAS CONFIGURADAS:")
print(f"   📁 Modelos: {MODELOS_DIR}")
print(f"   📁 Videos: {VIDEOS_DIR}")
print(f"   📁 Resultados: {RESULTADOS_BASE}")

# ============================================================================
# ENCONTRAR EL MODELO MÁS RECIENTE
# ============================================================================

def encontrar_modelo_mas_reciente():
    """Encuentra el modelo con el número más alto en la carpeta Modelos"""
    print(f"\n🔍 BUSCANDO MODELO MÁS RECIENTE...")

    modelos = glob.glob(os.path.join(MODELOS_DIR, "best_*.pt"))

    if not modelos:
        print("❌ No se encontraron modelos en la carpeta Modelos")
        return None, None

    numeros_modelos = []
    for modelo_path in modelos:
        match = re.search(r'best_(\d+)\.pt', os.path.basename(modelo_path))
        if match:
            numero = int(match.group(1))
            numeros_modelos.append((numero, modelo_path))

    if not numeros_modelos:
        print("❌ No se pudieron extraer números de los modelos")
        return None, None

    numeros_modelos.sort(key=lambda x: x[0], reverse=True)
    numero_mas_alto, modelo_mas_reciente = numeros_modelos[0]

    print(f"✅ Modelo más reciente encontrado:")
    print(f"   🔢 Número: {numero_mas_alto}")
    print(f"   📁 Ruta: {modelo_mas_reciente}")

    return numero_mas_alto, modelo_mas_reciente

# Encontrar el modelo más reciente
NUMERO_MODELO, MODELO_PATH = encontrar_modelo_mas_reciente()

if MODELO_PATH is None:
    print("❌ No se pudo encontrar un modelo válido")
    exit()

# ============================================================================
# CREAR CARPETA DE RESULTADOS
# ============================================================================

CARPETA_RESULTADOS = os.path.join(RESULTADOS_BASE, f"Analizando_con_modelo_{NUMERO_MODELO:02d}")
CARPETA_ANOTACIONES = os.path.join(CARPETA_RESULTADOS, "anotaciones")

os.makedirs(CARPETA_RESULTADOS, exist_ok=True)
os.makedirs(CARPETA_ANOTACIONES, exist_ok=True)

print(f"\n📁 CARPETAS DE RESULTADOS CREADAS:")
print(f"   📂 Videos procesados: {CARPETA_RESULTADOS}")
print(f"   📂 Anotaciones: {CARPETA_ANOTACIONES}")

# ============================================================================
# CARGAR EL MODELO
# ============================================================================

print(f"\n🔄 CARGANDO MODELO...")

try:
    modelo = YOLO(MODELO_PATH)
    print(f"✅ Modelo cargado exitosamente")
    print(f"🎯 Tipo: {modelo.task}")
    print(f"🏷️  Clases: {len(modelo.names)}")
    print(f"📊 Clases disponibles: {list(modelo.names.values())}")

except Exception as e:
    print(f"❌ Error cargando el modelo: {e}")
    exit()

# ============================================================================
# ENCONTRAR VIDEOS PARA PROCESAR
# ============================================================================

def encontrar_videos():
    """Encuentra todos los videos en la carpeta de videos"""
    print(f"\n🔍 BUSCANDO VIDEOS...")

    extensiones = ['*.mp4', '*.avi', '*.mov', '*.mkv', '*.wmv', '*.flv', '*.webm']
    videos_encontrados = []

    for extension in extensiones:
        videos_encontrados.extend(glob.glob(os.path.join(VIDEOS_DIR, extension)))
        videos_encontrados.extend(glob.glob(os.path.join(VIDEOS_DIR, extension.upper())))

    videos_encontrados = list(set(videos_encontrados))
    videos_encontrados.sort()

    print(f"✅ Videos encontrados: {len(videos_encontrados)}")
    for video in videos_encontrados:
        print(f"   🎥 {os.path.basename(video)}")

    return videos_encontrados

videos = encontrar_videos()

if not videos:
    print("❌ No se encontraron videos para procesar")
    exit()

# ============================================================================
# FUNCIÓN CORREGIDA PARA GUARDAR ANOTACIONES DE SEGMENTACIÓN
# ============================================================================

def guardar_anotaciones_segmentacion(results, frame_num, video_nombre, carpeta_anotaciones, frame_width, frame_height):
    """Guarda las anotaciones de SEGMENTACIÓN (polígonos) en archivos de texto"""

    # Crear nombre de archivo para este frame
    nombre_archivo = f"{video_nombre}_frame_{frame_num:06d}.txt"
    ruta_anotacion = os.path.join(carpeta_anotaciones, nombre_archivo)

    with open(ruta_anotacion, 'w') as f:
        # Verificar si hay detecciones
        if results[0].masks is not None and len(results[0].masks) > 0:
            # Obtener todas las detecciones de segmentación
            boxes = results[0].boxes
            masks = results[0].masks

            # Convertir a numpy de forma segura
            def safe_to_numpy(tensor_or_array):
                if hasattr(tensor_or_array, 'cpu'):  # Es un tensor de PyTorch
                    return tensor_or_array.cpu().numpy()
                else:  # Ya es un array de numpy
                    return tensor_or_array

            classes = safe_to_numpy(boxes.cls)
            confidences = safe_to_numpy(boxes.conf)

            # Escribir cada detección de segmentación
            for i in range(len(classes)):
                class_id = int(classes[i])
                class_name = results[0].names[class_id]
                confidence = confidences[i]

                # Obtener el polígono de segmentación
                if masks[i] is not None:
                    try:
                        # Obtener coordenadas del polígono - manejar diferentes formatos
                        if hasattr(masks[i].xy[0], 'cpu'):
                            polygon = masks[i].xy[0].cpu().numpy()  # Forma: (n, 2)
                        else:
                            polygon = masks[i].xy[0]  # Ya es numpy array

                        # Convertir a formato normalizado (0-1)
                        polygon_normalized = polygon / np.array([frame_width, frame_height])

                        # Aplanar el polígono para guardarlo
                        polygon_flat = polygon_normalized.reshape(-1)

                        # Escribir en formato: clase confianza x1 y1 x2 y2 ... xn yn
                        linea = f"{class_id} {confidence:.4f} " + " ".join([f"{coord:.6f}" for coord in polygon_flat]) + "\n"
                        f.write(linea)

                    except Exception as e:
                        print(f"⚠️  Error procesando máscara {i}: {e}")
                        # Fallback a bounding box si hay error con la máscara
                        if boxes.xyxy is not None:
                            bbox = safe_to_numpy(boxes.xyxy[i])
                            x1, y1, x2, y2 = bbox
                            # Convertir bbox a formato de polígono (4 puntos)
                            bbox_polygon = np.array([[x1, y1], [x2, y1], [x2, y2], [x1, y2]])
                            bbox_normalized = bbox_polygon / np.array([frame_width, frame_height])
                            bbox_flat = bbox_normalized.reshape(-1)
                            linea = f"{class_id} {confidence:.4f} " + " ".join([f"{coord:.6f}" for coord in bbox_flat]) + "\n"
                            f.write(linea)
                else:
                    # Si no hay máscara, usar bounding box como fallback
                    if boxes.xyxy is not None:
                        bbox = safe_to_numpy(boxes.xyxy[i])
                        x1, y1, x2, y2 = bbox
                        # Convertir bbox a formato de polígono (4 puntos)
                        bbox_polygon = np.array([[x1, y1], [x2, y1], [x2, y2], [x1, y2]])
                        bbox_normalized = bbox_polygon / np.array([frame_width, frame_height])
                        bbox_flat = bbox_normalized.reshape(-1)
                        linea = f"{class_id} {confidence:.4f} " + " ".join([f"{coord:.6f}" for coord in bbox_flat]) + "\n"
                        f.write(linea)
        else:
            # No hay detecciones en este frame
            f.write("# Sin detecciones en este frame\n")

    return ruta_anotacion

# ============================================================================
# FUNCIÓN MEJORADA PARA PROCESAR VIDEO CON ANOTACIONES DE SEGMENTACIÓN
# ============================================================================

def procesar_video_con_segmentacion(video_path, modelo, numero_modelo, carpeta_resultados, carpeta_anotaciones):
    """Procesa un video completo guardando video y anotaciones de SEGMENTACIÓN"""

    nombre_video = os.path.basename(video_path)
    nombre_sin_extension = os.path.splitext(nombre_video)[0]
    video_salida = os.path.join(carpeta_resultados, f"{nombre_sin_extension}_modelo_{numero_modelo:02d}.mp4")

    print(f"\n🎬 PROCESANDO VIDEO: {nombre_video}")
    print(f"   📁 Salida video: {os.path.basename(video_salida)}")
    print(f"   📁 Anotaciones: {carpeta_anotaciones}")

    try:
        # Abrir el video
        cap = cv2.VideoCapture(video_path)
        if not cap.isOpened():
            print(f"   ❌ No se pudo abrir el video: {video_path}")
            return False

        # Obtener propiedades del video
        fps = int(cap.get(cv2.CAP_PROP_FPS))
        width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

        print(f"   📊 Propiedades: {width}x{height}, {fps} FPS, {total_frames} frames")

        # Configurar video de salida
        fourcc = cv2.VideoWriter_fourcc(*'mp4v')
        out = cv2.VideoWriter(video_salida, fourcc, fps, (width, height))

        frame_count = 0
        frames_procesados = 0
        anotaciones_guardadas = 0

        # Procesar cada frame
        while True:
            ret, frame = cap.read()
            if not ret:
                break

            frame_count += 1

            # Procesar frame
            procesar_frame = True

            if procesar_frame:
                # Realizar predicción
                results = modelo(frame, verbose=False)

                # GUARDAR ANOTACIONES DE SEGMENTACIÓN EN ARCHIVO TEXTO
                try:
                    ruta_anotacion = guardar_anotaciones_segmentacion(
                        results, frame_count, nombre_sin_extension, carpeta_anotaciones, width, height
                    )
                    anotaciones_guardadas += 1
                except Exception as e:
                    print(f"   ❌ Error guardando anotaciones para frame {frame_count}: {e}")
                    # Crear archivo vacío para mantener la consistencia
                    nombre_archivo = f"{nombre_sin_extension}_frame_{frame_count:06d}.txt"
                    ruta_anotacion = os.path.join(carpeta_anotaciones, nombre_archivo)
                    with open(ruta_anotacion, 'w') as f:
                        f.write("# Error procesando este frame\n")

                # Dibujar resultados en el frame
                annotated_frame = results[0].plot()

                # Escribir frame procesado
                out.write(annotated_frame)
                frames_procesados += 1
            else:
                # Escribir frame original sin procesar
                out.write(frame)

            # Mostrar progreso cada 100 frames
            if frame_count % 100 == 0:
                print(f"   📈 Progreso: {frame_count}/{total_frames} frames | Anotaciones: {anotaciones_guardadas}")

        # Liberar recursos
        cap.release()
        out.release()

        print(f"   ✅ Video procesado: {frames_procesados}/{frame_count} frames")
        print(f"   ✅ Anotaciones de segmentación guardadas: {anotaciones_guardadas} archivos .txt")
        return True

    except Exception as e:
        print(f"   ❌ Error procesando video {nombre_video}: {e}")
        return False

# ============================================================================
# PROCESAR TODOS LOS VIDEOS
# ============================================================================

print(f"\n🚀 INICIANDO PROCESAMIENTO DE VIDEOS CON SEGMENTACIÓN...")
print("⏰ Esto puede tomar tiempo...")

videos_exitosos = 0
videos_fallidos = 0

for i, video_path in enumerate(videos, 1):
    print(f"\n{'='*60}")
    print(f"📹 PROCESANDO VIDEO {i}/{len(videos)}")

    exito = procesar_video_con_segmentacion(video_path, modelo, NUMERO_MODELO, CARPETA_RESULTADOS, CARPETA_ANOTACIONES)

    if exito:
        videos_exitosos += 1
    else:
        videos_fallidos += 1

# ============================================================================
# GENERAR REPORTE FINAL
# ============================================================================

print(f"\n🎉 PROCESAMIENTO COMPLETADO!")
print("=" * 60)
print(f"📊 RESUMEN FINAL:")
print(f"   ✅ Videos procesados exitosamente: {videos_exitosos}")
print(f"   ❌ Videos con errores: {videos_fallidos}")
print(f"   📁 Carpeta de videos: {CARPETA_RESULTADOS}")
print(f"   📁 Carpeta de anotaciones: {CARPETA_ANOTACIONES}")
print(f"   🎯 Modelo utilizado: best_{NUMERO_MODELO:02d}.pt")
print("=" * 60)

# Contar archivos de anotaciones
anotaciones_totales = len(glob.glob(os.path.join(CARPETA_ANOTACIONES, "*.txt")))
print(f"   📄 Total de archivos de anotaciones: {anotaciones_totales}")

# Crear archivo de reporte
reporte_path = os.path.join(CARPETA_RESULTADOS, f"reporte_modelo_{NUMERO_MODELO:02d}.txt")
with open(reporte_path, 'w') as f:
    f.write(f"REPORTE DE ANÁLISIS DE VIDEOS CON SEGMENTACIÓN\n")
    f.write("=" * 50 + "\n")
    f.write(f"Modelo utilizado: best_{NUMERO_MODELO:02d}.pt\n")
    f.write(f"Tipo de modelo: {modelo.task}\n")
    f.write(f"Clases: {len(modelo.names)}\n")
    f.write(f"Videos procesados: {videos_exitosos}/{len(videos)}\n")
    f.write(f"Archivos de anotaciones: {anotaciones_totales}\n")
    f.write(f"Formato de anotaciones: Segmentación (polígonos normalizados)\n")
    f.write(f"Fecha de procesamiento: {os.popen('date').read().strip()}\n\n")

    f.write("LISTA DE VIDEOS PROCESADOS:\n")
    for video in videos:
        nombre = os.path.basename(video)
        f.write(f"- {nombre}\n")

print(f"📄 Reporte guardado en: {reporte_path}")

# Mostrar ejemplo de anotación de segmentación
print(f"\n📝 EJEMPLO DE ANOTACIÓN DE SEGMENTACIÓN GUARDADA:")
archivos_anotacion = glob.glob(os.path.join(CARPETA_ANOTACIONES, "*.txt"))
if archivos_anotacion:
    primer_anotacion = archivos_anotacion[0]
    print(f"   Archivo: {os.path.basename(primer_anotacion)}")
    with open(primer_anotacion, 'r') as f:
        primeras_lineas = f.readlines()[:2]  # Mostrar primeras 2 líneas
        for i, linea in enumerate(primeras_lineas):
            partes = linea.strip().split()
            if len(partes) > 2 and not linea.startswith("#"):
                class_id = partes[0]
                confidence = partes[1]
                num_puntos = (len(partes) - 2) // 2
                class_name = modelo.names[int(class_id)] if class_id.isdigit() else class_id
                print(f"   → {class_name} {confidence} [Polígono con {num_puntos} puntos]")
            else:
                print(f"   → {linea.strip()}")

print(f"\n🚀 ¡PROCESO COMPLETADO! Ahora tienes:")
print(f"   🎥 Videos procesados en: {CARPETA_RESULTADOS}")
print(f"   📄 Anotaciones de SEGMENTACIÓN en: {CARPETA_ANOTACIONES}")