# -*- coding: utf-8 -*-
"""Modelo2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WuO_5mWsWlGeNyMlqxWQ5YJlVIZ7vWU0
"""

# Verificar GPU
!nvidia-smi


# Montar Google Drive
from google.colab import drive
drive.mount('/content/drive')


# Crear estructura de carpetas
!mkdir -p '/content/drive/MyDrive/TFG_Modelo2'
!mkdir -p '/content/drive/MyDrive/TFG_Modelo2/dataset'
!mkdir -p '/content/drive/MyDrive/TFG_Modelo2/results'
!mkdir -p '/content/drive/MyDrive/TFG_Modelo2/videos'

# Instalar Ultralytics (YOLOv8)
!pip install ultralytics


# Verificar instalación
import ultralytics
print(f"Ultralytics version: {ultralytics.__version__}")

# Opción: Renombrar a un nombre sin espacios
!cp "/content/drive/MyDrive/Datas/TFG -JBC-FINAL-DATA-3.v1i.yolov8.zip" "/content/TFG-JBC-FINAL-DATA-3.v1i.yolov8.zip"


# Luego descomprimir con el nuevo nombre
!unzip -q "/content/TFG-JBC-FINAL-DATA-3.v1i.yolov8.zip" -d "/content/dataset_seg"

# Verificar que las anotaciones son de segmentación (polígonos)
import os


def check_segmentation_annotations(dataset_path):
    labels_path = os.path.join(dataset_path, 'train', 'labels')
    if os.path.exists(labels_path):
        sample_files = os.listdir(labels_path)[:3]
        for file in sample_files:
            file_path = os.path.join(labels_path, file)
            with open(file_path, 'r') as f:
                lines = f.readlines()
                if lines:
                    first_line = lines[0].strip().split()
                    print(f"{file}: {len(first_line)} valores")
                    if len(first_line) > 5:
                        print("✅ Formato de SEGMENTACIÓN (polígonos)")
                    else:
                        print("❌ Formato de DETECCIÓN (bounding boxes)")


check_segmentation_annotations('/content/dataset_seg')

# Verificar y corregir data.yaml
with open('/content/dataset_seg/data.yaml', 'r') as f:
    content = f.read()
    print("Contenido actual de data.yaml:")
    print(content)


# Corregir rutas si es necesario
content = content.replace('../train/images', '/content/dataset_seg/train/images')
content = content.replace('../valid/images', '/content/dataset_seg/valid/images')
content = content.replace('../test/images', '/content/dataset_seg/test/images')


with open('/content/dataset_seg/data.yaml', 'w') as f:
    f.write(content)


print("✅ data.yaml configurado para segmentación")

from ultralytics import YOLO
import torch
import time

# Verificar recursos
print(f"GPU disponible: {torch.cuda.is_available()}")
print(f"GPU: {torch.cuda.get_device_name(0)}")

# Cálculo: 24 épocas/hora × 2.8 horas (con margen) = 67 épocas
EPOCHS_TARGET = 67

# Modelo pequeño pero manteniendo 640x640
model = YOLO('yolov8s-seg.pt')  # Small para velocidad

# Configuración optimizada manteniendo 640x640
training_config = {
    'data': '/content/dataset_seg/data.yaml',
    'epochs': EPOCHS_TARGET,
    'patience': 15,
    'batch': 12,                       # Reducido batch para compensar 640x640
    'imgsz': 640,                      # ✅ MANTENEMOS 640x640
    'lr0': 0.01,
    'lrf': 0.01,
    'momentum': 0.937,
    'weight_decay': 0.0005,
    'warmup_epochs': 1.0,
    'save': True,
    'save_period': 15,
    'cache': False,
    'workers': 8,                      # Workers moderados
    'device': 0,
    'project': '/content/drive/MyDrive/TFG_Modelo2',
    'name': f'yolov8s_seg_640_{int(time.time())}',
    'exist_ok': True,
    'pretrained': True,
    'optimizer': 'SGD',
    'verbose': False,
    'single_cls': False,
    'overlap_mask': True,
    'mask_ratio': 2,
    'close_mosaic': 5,
    # Augmentaciones mínimas pero no cero
    'hsv_h': 0.015,                    # Muy poco aumento de color
    'hsv_s': 0.7,
    'hsv_v': 0.4,
    'degrees': 5.0,                    # Rotación mínima
    'translate': 0.1,
    'scale': 0.2,
    'fliplr': 0.5,                     # Solo flip horizontal
    'mosaic': 0.5,                     # Mosaic reducido
}

print(f"🎯 INICIANDO ENTRENAMIENTO CON 640x640")
print(f"   ⏱️  Objetivo: {EPOCHS_TARGET} épocas (~2.8 horas)")
print(f"   🧠 Modelo: YOLOv8s-seg")
print(f"   🖼️  Tamaño: 640x640 (como solicitaste)")
print(f"   📊 Batch size: 12")
print(f"   🔄 Augmentaciones: Mínimas")

# Iniciar entrenamiento
start_time = time.time()
results = model.train(**training_config)
end_time = time.time()

training_duration = (end_time - start_time) / 3600
print(f"✅ ENTRENAMIENTO COMPLETADO")
print(f"⏱️  Duración: {training_duration:.2f} horas")

# Importar librerías necesarias
from ultralytics import YOLO
import os
from google.colab import files
from IPython.display import HTML, display
import cv2

# Cargar el modelo entrenado
model_path = '/content/drive/MyDrive/TFG_Modelo2/yolov8s_seg_640_1761761516/weights/best.pt'
best_model = YOLO(model_path)

print("✅ Modelo cargado correctamente")

import os
import cv2
from ultralytics import YOLO
import shutil

# Cargar el modelo entrenado
print("🚀 CARGANDO MODELO ENTRENADO...")
model_path = '/content/drive/MyDrive/TFG_Modelo2/yolov8s_seg_640_1761761516/weights/best.pt'
best_model = YOLO(model_path)
print("✅ MODELO CARGADO")

# Función mejorada para procesar videos
def process_video(input_path, output_path, conf=0.5):
    """
    Procesa un video con el modelo de segmentación YOLOv8
    """
    print(f"🎥 PROCESANDO VIDEO: {input_path}")

    # Verificar que el video existe
    if not os.path.exists(input_path):
        print(f"❌ ERROR: El video no existe en {input_path}")
        return None

    # Extraer información del video de entrada
    video_name = os.path.splitext(os.path.basename(input_path))[0]

    # YOLO guarda los resultados en una carpeta 'predict' por defecto
    # Vamos a controlar explícitamente dónde se guarda
    try:
        # Realizar predicción en el video
        results = best_model.predict(
            source=input_path,
            conf=conf,
            save=True,  # Esto hace que YOLO guarde el video
            project=os.path.dirname(output_path),
            name=video_name + "_results",
            exist_ok=True  # Sobrescribir si existe
        )

        # BUSCAR DÓNDE GUARDÓ YOLO EL VIDEO
        print("🔍 BUSCANDO EL VIDEO PROCESADO...")

        # Rutas donde YOLO podría haber guardado el video
        possible_paths = [
            os.path.join(os.path.dirname(output_path), video_name + "_results", video_name + ".mp4"),
            os.path.join(os.path.dirname(output_path), video_name + "_results", "video.mp4"),
            os.path.join(os.path.dirname(output_path), video_name + "_results", os.path.basename(input_path)),
            f"/content/runs/segment/{video_name}_results/{os.path.basename(input_path)}",
            f"/content/runs/segment/predict/{os.path.basename(input_path)}",
            f"/content/runs/segment/predict/video.mp4"
        ]

        found_video = None
        for path in possible_paths:
            if os.path.exists(path):
                found_video = path
                print(f"✅ VIDEO ENCONTRADO EN: {path}")
                break

        if found_video:
            # Copiar el video a la ubicación deseada
            shutil.copy(found_video, output_path)
            print(f"✅ VIDEO COPIADO A: {output_path}")

            # Mostrar información del video procesado
            cap = cv2.VideoCapture(output_path)
            fps = cap.get(cv2.CAP_PROP_FPS)
            frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
            cap.release()

            print(f"📊 INFORMACIÓN DEL VIDEO:")
            print(f"   - FPS: {fps}")
            print(f"   - Frames: {frame_count}")
            print(f"   - Duración: {frame_count/fps:.2f} segundos")

            return results
        else:
            print("❌ NO SE PUDO ENCONTRAR EL VIDEO PROCESADO")
            print("🔍 BUSCANDO EN TODAS LAS CARPETAS...")

            # Buscar recursivamente
            for root, dirs, files in os.walk('/content/'):
                for file in files:
                    if file.endswith('.mp4') and video_name in file:
                        found_path = os.path.join(root, file)
                        print(f"🎥 POSIBLE VIDEO: {found_path}")

            return None

    except Exception as e:
        print(f"❌ ERROR durante el procesamiento: {e}")
        return None

# VERIFICAR ESTRUCTURA DE CARPETAS ANTES DE PROCESAR
print("📁 VERIFICANDO ESTRUCTURA DE CARPETAS...")
base_dir = "/content/drive/MyDrive/TFG_Modelo2"
videos_dir = os.path.join(base_dir, "videos")
output_dir = os.path.join(base_dir, "videos_procesados")

print(f"📂 Directorio base: {base_dir}")
print(f"📂 Videos originales: {videos_dir}")
print(f"📂 Salida deseada: {output_dir}")

# Crear directorios si no existen
os.makedirs(videos_dir, exist_ok=True)
os.makedirs(output_dir, exist_ok=True)

# Listar contenido de las carpetas
print(f"\n📄 CONTENIDO DE {videos_dir}:")
if os.path.exists(videos_dir):
    for item in os.listdir(videos_dir):
        print(f"   - {item}")
else:
    print("   ❌ No existe")

print(f"\n📄 CONTENIDO DE {output_dir}:")
if os.path.exists(output_dir):
    for item in os.listdir(output_dir):
        print(f"   - {item}")
else:
    print("   ❌ No existe")

# PROCESAR LOS VIDEOS ESPECÍFICOS
videos_a_procesar = [
    "/content/drive/MyDrive/TFG_Modelo2/videos/prueba1.mp4",
    "/content/drive/MyDrive/TFG_Modelo2/videos/prueba2.mp4"
]

print(f"\n🎯 INICIANDO PROCESAMIENTO DE {len(videos_a_procesar)} VIDEOS...")

for input_video in videos_a_procesar:
    if os.path.exists(input_video):
        # Crear nombre de salida
        video_name = os.path.splitext(os.path.basename(input_video))[0]
        output_video = os.path.join(output_dir, f"segmentado_{video_name}.mp4")

        print(f"\n{'='*60}")
        print(f"🎬 PROCESANDO: {os.path.basename(input_video)}")
        print(f"💾 GUARDANDO COMO: {os.path.basename(output_video)}")
        print(f"{'='*60}")

        # Procesar el video
        process_video(input_video, output_video, conf=0.5)

        # Verificar que se creó el archivo
        if os.path.exists(output_video):
            file_size = os.path.getsize(output_video) / (1024*1024)  # MB
            print(f"✅ VERIFICACIÓN: Archivo creado ({file_size:.1f} MB)")
        else:
            print("❌ VERIFICACIÓN: El archivo NO se creó en la ubicación esperada")
    else:
        print(f"❌ El video no existe: {input_video}")

# VERIFICACIÓN FINAL
print(f"\n📋 VERIFICACIÓN FINAL - CONTENIDO DE {output_dir}:")
if os.path.exists(output_dir):
    for item in os.listdir(output_dir):
        item_path = os.path.join(output_dir, item)
        if os.path.isfile(item_path):
            size = os.path.getsize(item_path) / (1024*1024)
            print(f"   📄 {item} ({size:.1f} MB)")
        else:
            print(f"   📂 {item}/")
else:
    print("   ❌ El directorio no existe")

print("\n🎉 PROCESAMIENTO COMPLETADO")

import os

# RUTA CORREGIDA - Sin "TFG_Modelo2"
VIDEOS_FOLDER = "/content/drive/MyDrive/Videos_TFG"

print("🔍 BUSCANDO CARPETA DE VIDEOS...")
print(f"Ruta: {VIDEOS_FOLDER}")

# Verificar si existe la carpeta
if os.path.exists(VIDEOS_FOLDER):
    print("✅ Carpeta encontrada")

    # Listar todos los archivos en la carpeta
    todos_los_archivos = os.listdir(VIDEOS_FOLDER)
    print(f"📁 Archivos en la carpeta: {len(todos_los_archivos)}")

    # Filtrar solo videos
    videos = [f for f in todos_los_archivos if f.endswith(('.mp4', '.avi', '.mov', '.mkv'))]
    print(f"🎥 Videos encontrados: {len(videos)}")

    if videos:
        print("📹 LISTA DE VIDEOS:")
        for i, video in enumerate(videos):
            ruta_completa = os.path.join(VIDEOS_FOLDER, video)
            tamaño_mb = os.path.getsize(ruta_completa) / (1024*1024)
            print(f"   {i+1}. {video} ({tamaño_mb:.1f} MB)")
    else:
        print("❌ No se encontraron videos en la carpeta")

else:
    print("❌ La carpeta de videos NO existe")
    print("💡 Creando la carpeta...")
    os.makedirs(VIDEOS_FOLDER, exist_ok=True)
    print(f"✅ Carpeta creada: {VIDEOS_FOLDER}")

import cv2

# Configuración del video específico
VIDEO_NAME = "prueba1.mp4"
VIDEO_PATH = f"/content/drive/MyDrive/Videos_TFG/{VIDEO_NAME}"

print("🎥 ANALIZANDO EL VIDEO...")
print(f"Video: {VIDEO_PATH}")

# Verificar que el video existe
if not os.path.exists(VIDEO_PATH):
    print("❌ ERROR: El video no existe")
else:
    print("✅ Video encontrado")

    # Abrir el video con OpenCV
    cap = cv2.VideoCapture(VIDEO_PATH)

    if not cap.isOpened():
        print("❌ ERROR: No se puede abrir el video")
    else:
        # Obtener información del video
        fps = cap.get(cv2.CAP_PROP_FPS)
        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        duration = total_frames / fps if fps > 0 else 0

        print("📊 INFORMACIÓN DEL VIDEO:")
        print(f"   📏 Resolución: {width} x {height}")
        print(f"   ⏱️  FPS: {fps:.2f}")
        print(f"   📦 Frames totales: {total_frames}")
        print(f"   🕒 Duración: {duration:.2f} segundos")

        # Leer el primer frame para verificar
        ret, first_frame = cap.read()
        if ret:
            print(f"   🖼️ Primer frame: {first_frame.shape}")
        else:
            print("   ❌ No se pudo leer el primer frame")

        # Cerrar el video
        cap.release()

# Calcular frames recomendados para extraer
if 'total_frames' in locals() and total_frames > 0:
    print(f"\n💡 RECOMENDACIONES:")

    # Diferentes opciones de extracción
    opciones = [
        ("Alta densidad", 1, total_frames),
        ("Media densidad", 10, total_frames // 10),
        ("Baja densidad", 30, total_frames // 30),
        ("Solo clave", 100, total_frames // 100)
    ]

    for nombre, intervalo, frames in opciones:
        print(f"   {nombre}: cada {intervalo} frames → ~{frames} imágenes")

import cv2
import os

# Configuración para media densidad
VIDEO_NAME = "prueba1.mp4"
VIDEO_PATH = f"/content/drive/MyDrive/Videos_TFG/{VIDEO_NAME}"
OUTPUT_FOLDER = f"/content/drive/MyDrive/frames_{VIDEO_NAME.split('.')[0]}"

# Parámetros de extracción
FRAME_INTERVAL = 10  # 1 de cada 10 frames
MAX_FRAMES = 150     # Máximo por si acaso

print("🚀 CONFIGURANDO EXTRACCIÓN...")
print(f"Video: {VIDEO_NAME}")
print(f"Salida: {OUTPUT_FOLDER}")
print(f"Intervalo: cada {FRAME_INTERVAL} frames")
print(f"Máximo: {MAX_FRAMES} frames")

# Crear carpeta de salida
os.makedirs(OUTPUT_FOLDER, exist_ok=True)
print(f"✅ Carpeta creada: {OUTPUT_FOLDER}")

# Iniciar extracción
cap = cv2.VideoCapture(VIDEO_PATH)
frame_count = 0
saved_count = 0

print("\n🔄 EXTRAYENDO FRAMES...")

while True:
    ret, frame = cap.read()

    if not ret:
        break

    # Extraer cada 10 frames
    if frame_count % FRAME_INTERVAL == 0:
        # Guardar frame
        filename = f"frame_{saved_count:04d}.jpg"
        output_path = os.path.join(OUTPUT_FOLDER, filename)
        cv2.imwrite(output_path, frame)
        saved_count += 1

        # Mostrar progreso cada 10 frames guardados
        if saved_count % 10 == 0:
            print(f"   📸 {saved_count} frames guardados...")

    frame_count += 1

    # Detener si alcanzamos el máximo
    if saved_count >= MAX_FRAMES:
        break

cap.release()

print(f"\n✅ EXTRACCIÓN COMPLETADA!")
print(f"   Frames procesados: {frame_count}")
print(f"   Frames guardados: {saved_count}")
print(f"   Carpeta: {OUTPUT_FOLDER}")

# Verificar que se crearon los archivos
archivos_creados = len([f for f in os.listdir(OUTPUT_FOLDER) if f.endswith('.jpg')])
print(f"   Archivos en carpeta: {archivos_creados}")

import os

# Verificación del dataset
def verificar_dataset():
    data_yaml_path = '/content/drive/MyDrive/Datas/New_Data.v1i.yolov8/data.yaml'

    if os.path.exists(data_yaml_path):
        print(f"✅ data.yaml encontrado")
        with open(data_yaml_path, 'r') as f:
            content = f.read()
            print("📄 Contenido de data.yaml:")
            print(content)
    else:
        print(f"❌ data.yaml no encontrado")

        # Buscar archivos .yaml en la carpeta
        dataset_dir = '/content/drive/MyDrive/Datas/New_Data.v1i.yolov8'
        if os.path.exists(dataset_dir):
            print(f"🔍 Buscando archivos en: {dataset_dir}")
            for file in os.listdir(dataset_dir):
                if file.endswith('.yaml') or file.endswith('.yml'):
                    print(f"   📄 {file}")

verificar_dataset()

import os

# Mira qué clases tienen realmente tus etiquetas
def investigar_clases():
    print("🔍 INVESTIGANDO LAS CLASES...")

    # Revisar el nuevo dataset
    nuevo_dataset = '/content/drive/MyDrive/Datas/New_Data.v1i.yolov8'

    for split in ['train', 'val']:
        labels_dir = os.path.join(nuevo_dataset, split, 'labels')

        if os.path.exists(labels_dir):
            print(f"\n📂 Revisando {split} del NUEVO dataset:")

            clases_encontradas = set()
            for archivo in os.listdir(labels_dir):
                if archivo.endswith('.txt'):
                    with open(os.path.join(labels_dir, archivo), 'r') as f:
                        for linea in f:
                            clase = linea.split()[0]  # La primera número es la clase
                            clases_encontradas.add(clase)

            print(f"   Clases encontradas: {sorted(clases_encontradas)}")

investigar_clases()

import os
import shutil

# ============================================================================
# CONFIGURACIÓN DE RUTAS
# ============================================================================

# Rutas de origen
dataset_original = '/content/dataset_seg'
dataset_nuevo = '/content/drive/MyDrive/Datas/New_Data.v1i.yolov8'

# Ruta de destino
dataset_combinado = '/content/dataset_combinado_paso_a_paso'

print("📍 CONFIGURACIÓN DE RUTAS:")
print(f"   Original: {dataset_original}")
print(f"   Nuevo: {dataset_nuevo}")
print(f"   Combinado: {dataset_combinado}")

# ============================================================================
# PASO 1: VERIFICAR ESTRUCTURA ORIGINAL (CON valid)
# ============================================================================

def verificar_estructura_original():
    print("\n" + "="*60)
    print("🔍 PASO 1: VERIFICANDO ESTRUCTURA ORIGINAL")
    print("="*60)

    datasets = [
        ("ORIGINAL", dataset_original),
        ("NUEVO", dataset_nuevo)
    ]

    for nombre, ruta in datasets:
        print(f"\n📁 {nombre}: {ruta}")

        if not os.path.exists(ruta):
            print(f"   ❌ No existe")
            continue

        # Verificar tanto 'val' como 'valid'
        for split in ['train', 'val', 'valid', 'test']:
            split_path = os.path.join(ruta, split)
            if os.path.exists(split_path):
                images_dir = os.path.join(split_path, 'images')
                labels_dir = os.path.join(split_path, 'labels')

                images_count = len([f for f in os.listdir(images_dir) if f.endswith(('.jpg', '.png'))]) if os.path.exists(images_dir) else 0
                labels_count = len([f for f in os.listdir(labels_dir) if f.endswith('.txt')]) if os.path.exists(labels_dir) else 0

                print(f"   📂 {split}:")
                print(f"      🖼️  Imágenes: {images_count}")
                print(f"      📝 Etiquetas: {labels_count}")

                # Mostrar algunas clases de ejemplo
                if labels_count > 0:
                    clases_ejemplo = set()
                    for label_file in list(os.listdir(labels_dir))[:3]:  # Primeras 3 etiquetas
                        label_path = os.path.join(labels_dir, label_file)
                        with open(label_path, 'r') as f:
                            for linea in f:
                                clase = linea.strip().split()[0]
                                clases_ejemplo.add(clase)
                    print(f"      🎯 Clases ejemplo: {clases_ejemplo}")
            else:
                if split in ['val', 'valid']:  # Solo mostrar si no encuentra estos
                    print(f"   📂 {split}: No existe")

verificar_estructura_original()

# ============================================================================
# PASO 2: CREAR ESTRUCTURA DEL DATASET COMBINADO (CON valid)
# ============================================================================

print("\n" + "="*60)
print("📁 PASO 2: CREANDO ESTRUCTURA COMBINADA")
print("="*60)

# Crear estructura de carpetas con 'valid' en lugar de 'val'
for split in ['train', 'valid', 'test']:
    for tipo in ['images', 'labels']:
        os.makedirs(os.path.join(dataset_combinado, split, tipo), exist_ok=True)
        print(f"   ✅ Creando: {dataset_combinado}/{split}/{tipo}")

# ============================================================================
# PASO 3: COPIAR ARCHIVOS CON CONTEO (CON valid)
# ============================================================================

def copiar_archivos_con_conteo():
    print("\n" + "="*60)
    print("📋 PASO 3: COPIANDO ARCHIVOS")
    print("="*60)

    contadores_totales = {
        'train': {'images': 0, 'labels': 0},
        'valid': {'images': 0, 'labels': 0},
        'test': {'images': 0, 'labels': 0}
    }

    # Función para copiar archivos de un dataset
    def copiar_dataset(origen, prefijo, nombre_dataset):
        print(f"\n🔄 Copiando desde {nombre_dataset}...")

        # Mapeo: de 'val' en origen a 'valid' en destino si es necesario
        split_mapping = {
            'train': 'train',
            'val': 'valid',    # Convertir val → valid
            'valid': 'valid',  # Mantener valid
            'test': 'test'
        }

        for split_origen in ['train', 'val', 'valid', 'test']:
            split_destino = split_mapping.get(split_origen, split_origen)

            origen_images = os.path.join(origen, split_origen, 'images')
            origen_labels = os.path.join(origen, split_origen, 'labels')
            destino_images = os.path.join(dataset_combinado, split_destino, 'images')
            destino_labels = os.path.join(dataset_combinado, split_destino, 'labels')

            if os.path.exists(origen_images):
                # Copiar imágenes
                for archivo in os.listdir(origen_images):
                    if archivo.lower().endswith(('.jpg', '.jpeg', '.png')):
                        nuevo_nombre = f"{prefijo}_{archivo}"
                        shutil.copy2(
                            os.path.join(origen_images, archivo),
                            os.path.join(destino_images, nuevo_nombre)
                        )
                        contadores_totales[split_destino]['images'] += 1

                # Copiar etiquetas
                if os.path.exists(origen_labels):
                    for archivo in os.listdir(origen_labels):
                        if archivo.endswith('.txt'):
                            nuevo_nombre = f"{prefijo}_{archivo}"
                            shutil.copy2(
                                os.path.join(origen_labels, archivo),
                                os.path.join(destino_labels, nuevo_nombre)
                            )
                            contadores_totales[split_destino]['labels'] += 1

            if os.path.exists(origen_images) or os.path.exists(origen_labels):
                print(f"   📊 {split_origen} → {split_destino}: {contadores_totales[split_destino]['images']} imágenes, {contadores_totales[split_destino]['labels']} etiquetas")

    # Copiar ambos datasets
    copiar_dataset(dataset_original, 'orig', 'Dataset Original')
    copiar_dataset(dataset_nuevo, 'nuevo', 'Dataset Nuevo')

    return contadores_totales

# Ejecutar copia
contadores = copiar_archivos_con_conteo()

# ============================================================================
# PASO 4: RESUMEN DE LA COPIA (CON valid)
# ============================================================================

print("\n" + "="*60)
print("📊 PASO 4: RESUMEN FINAL DE LA COPIA")
print("="*60)

for split in ['train', 'valid', 'test']:
    print(f"   📂 {split.upper()}:")
    print(f"      🖼️  Imágenes: {contadores[split]['images']}")
    print(f"      📝 Etiquetas: {contadores[split]['labels']}")

total_imagenes = sum(contadores[split]['images'] for split in ['train', 'valid', 'test'])
total_etiquetas = sum(contadores[split]['labels'] for split in ['train', 'valid', 'test'])

print(f"\n   🎯 TOTALES:")
print(f"      🖼️  Imágenes: {total_imagenes}")
print(f"      📝 Etiquetas: {total_etiquetas}")

# ============================================================================
# PASO 5: VERIFICAR CLASES ANTES DE CORREGIR (CON valid)
# ============================================================================

def verificar_clases_antes():
    print("\n" + "="*60)
    print("🔍 PASO 5: VERIFICANDO CLASES (ANTES DE CORREGIR)")
    print("="*60)

    for split in ['train', 'valid', 'test']:
        labels_dir = os.path.join(dataset_combinado, split, 'labels')

        if not os.path.exists(labels_dir):
            print(f"   📂 {split}: No hay etiquetas")
            continue

        clases_encontradas = set()
        total_etiquetas = 0

        for archivo in os.listdir(labels_dir):
            if archivo.endswith('.txt'):
                total_etiquetas += 1
                with open(os.path.join(labels_dir, archivo), 'r') as f:
                    for linea in f:
                        partes = linea.strip().split()
                        if partes:
                            clases_encontradas.add(partes[0])

        print(f"   📂 {split}:")
        print(f"      📝 Etiquetas revisadas: {total_etiquetas}")
        print(f"      🎯 Clases encontradas: {sorted(clases_encontradas)}")

verificar_clases_antes()

# ============================================================================
# PASO 6: CORREGIR CLASES (CON valid)
# ============================================================================

def corregir_clases():
    print("\n" + "="*60)
    print("🔧 PASO 6: CORRIGIENDO CLASES")
    print("="*60)

    for split in ['train', 'valid', 'test']:
        labels_dir = os.path.join(dataset_combinado, split, 'labels')

        if not os.path.exists(labels_dir):
            continue

        archivos_corregidos = 0
        lineas_corregidas = 0

        for archivo in os.listdir(labels_dir):
            if archivo.endswith('.txt'):
                ruta_archivo = os.path.join(labels_dir, archivo)

                # Leer y corregir
                with open(ruta_archivo, 'r') as f:
                    lineas = f.readlines()

                nuevas_lineas = []
                for linea in lineas:
                    partes = linea.strip().split()
                    if len(partes) >= 5:
                        # Cambiar clase a 0
                        partes[0] = '0'
                        nuevas_lineas.append(' '.join(partes) + '\n')
                        lineas_corregidas += 1

                # Guardar corregido
                with open(ruta_archivo, 'w') as f:
                    f.writelines(nuevas_lineas)

                archivos_corregidos += 1

        print(f"   ✅ {split}:")
        print(f"      📝 Archivos corregidos: {archivos_corregidos}")
        print(f"      🔄 Líneas modificadas: {lineas_corregidas}")

corregir_clases()

# ============================================================================
# PASO 7: VERIFICAR CLASES DESPUÉS DE CORREGIR (CON valid)
# ============================================================================

def verificar_clases_despues():
    print("\n" + "="*60)
    print("✅ PASO 7: VERIFICANDO CLASES (DESPUÉS DE CORREGIR)")
    print("="*60)

    for split in ['train', 'valid', 'test']:
        labels_dir = os.path.join(dataset_combinado, split, 'labels')

        if not os.path.exists(labels_dir):
            print(f"   📂 {split}: No hay etiquetas")
            continue

        clases_encontradas = set()

        for archivo in os.listdir(labels_dir):
            if archivo.endswith('.txt'):
                with open(os.path.join(labels_dir, archivo), 'r') as f:
                    for linea in f:
                        partes = linea.strip().split()
                        if partes:
                            clases_encontradas.add(partes[0])

        print(f"   📂 {split}: Clases → {clases_encontradas}")

verificar_clases_despues()

# ============================================================================
# PASO 8: CREAR DATA.YAML (CON valid)
# ============================================================================

print("\n" + "="*60)
print("📄 PASO 8: CREANDO DATA.YAML")
print("="*60)

data_yaml_content = f"""path: {dataset_combinado}
train: train/images
val: valid/images  # ← ¡IMPORTANTE: usando 'valid' en lugar de 'val'!
test: test/images

nc: 1
names: ['player']
"""

data_yaml_path = os.path.join(dataset_combinado, 'data.yaml')
with open(data_yaml_path, 'w') as f:
    f.write(data_yaml_content)

print(f"✅ data.yaml creado en: {data_yaml_path}")
print("📄 Contenido:")
print(data_yaml_content)

# ============================================================================
# PASO 9: VERIFICACIÓN FINAL (CON valid)
# ============================================================================

print("\n" + "="*60)
print("🎯 PASO 9: VERIFICACIÓN FINAL COMPLETA")
print("="*60)

print("✅ PROCESO COMPLETADO EXITOSAMENTE!")
print(f"📁 Dataset combinado en: {dataset_combinado}")
print("\n📊 RESUMEN FINAL:")

for split in ['train', 'valid', 'test']:
    images_dir = os.path.join(dataset_combinado, split, 'images')
    labels_dir = os.path.join(dataset_combinado, split, 'labels')

    images_count = len([f for f in os.listdir(images_dir) if f.endswith(('.jpg', '.png'))]) if os.path.exists(images_dir) else 0
    labels_count = len([f for f in os.listdir(labels_dir) if f.endswith('.txt')]) if os.path.exists(labels_dir) else 0

    print(f"   📂 {split.upper()}:")
    print(f"      🖼️  Imágenes: {images_count}")
    print(f"      📝 Etiquetas: {labels_count}")

print(f"\n🚀 ¡Ya puedes usar el dataset combinado para entrenar!")
print(f"📍 Ruta del data.yaml: {data_yaml_path}")

from ultralytics import YOLO
import torch
import time
import os

# ============================================================================
# VERIFICACIÓN INICIAL
# ============================================================================

print("🔍 VERIFICANDO RECURSOS...")
print(f"GPU disponible: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")

# ============================================================================
# CONFIGURACIÓN DEL ENTRENAMIENTO
# ============================================================================

# Cargar TU modelo entrenado (no uno preentrenado de YOLO)
model_path = '/content/drive/MyDrive/TFG_Modelo2/yolov8s_seg_640_1761761516/weights/best.pt'
print(f"🚀 CARGANDO MODELO: {model_path}")

if not os.path.exists(model_path):
    print(f"❌ ERROR: No se encuentra el modelo en {model_path}")
else:
    model = YOLO(model_path)
    print("✅ MODELO CARGADO CORRECTAMENTE")

# Ruta del dataset combinado
dataset_combinado = '/content/dataset_combinado_paso_a_paso'
data_yaml_path = os.path.join(dataset_combinado, 'data.yaml')

print(f"📁 Dataset combinado: {dataset_combinado}")
print(f"📄 Archivo config: {data_yaml_path}")

# Verificar que existe el dataset
if not os.path.exists(data_yaml_path):
    print(f"❌ ERROR: No se encuentra data.yaml en {data_yaml_path}")
else:
    # Mostrar contenido del data.yaml
    with open(data_yaml_path, 'r') as f:
        print("📋 CONTENIDO DE data.yaml:")
        print(f.read())

# ============================================================================
# CONFIGURACIÓN OPTIMIZADA PARA FINE-TUNING
# ============================================================================

# Configuración para fine-tuning con dataset combinado
training_config = {
    'data': data_yaml_path,
    'epochs': 30,                       # ✅ Menos épocas que el original (67)
    'patience': 10,                      # ✅ Menos paciencia
    'batch': 8,                         # ✅ Batch más pequeño
    'imgsz': 640,                       # ✅ Mismo tamaño
    'lr0': 0.0001,                      # ✅ ✅✅ LEARNING RATE MUY BAJO (IMPORTANTE)
    'lrf': 0.0001,                      # ✅ LR final bajo
    'momentum': 0.937,
    'weight_decay': 0.0005,
    'warmup_epochs': 2,                 # ✅ Poco warmup
    'save': True,
    'save_period': 10,
    'cache': False,
    'workers': 4,                       # ✅ Menos workers
    'device': 0,
    'project': '/content/drive/MyDrive/TFG_Modelo2',
    'name': f'fine_tuned_combinado_{int(time.time())}',  # Nombre único
    'exist_ok': True,
    'pretrained': False,                # ✅ NO usar pretrained, ya usamos nuestro modelo
    'optimizer': 'SGD',
    'verbose': True,
    # Data augmentation para evitar overfitting
    'hsv_h': 0.015,
    'hsv_s': 0.7,
    'hsv_v': 0.4,
    'degrees': 5.0,
    'translate': 0.1,
    'scale': 0.2,
    'fliplr': 0.5,
}

print(f"\n🎯 CONFIGURACIÓN DEL FINE-TUNING:")
print(f"   📊 Dataset: Combinado (original + nuevo)")
print(f"   ⏱️  Épocas: 30 (vs 67 del entrenamiento original)")
print(f"   🔽 Learning rate: 0.0001 (10x menor que el original)")
print(f"   📦 Batch size: 8")
print(f"   🖼️  Tamaño imagen: 640x640")
print(f"   ⏰ Tiempo estimado: 30-50 minutos")

# ============================================================================
# VERIFICACIÓN FINAL ANTES DE ENTRENAR
# ============================================================================

def verificar_dataset_final():
    print(f"\n🔍 VERIFICACIÓN FINAL DEL DATASET:")

    for split in ['train', 'valid', 'test']:
        images_dir = os.path.join(dataset_combinado, split, 'images')
        labels_dir = os.path.join(dataset_combinado, split, 'labels')

        images_count = len([f for f in os.listdir(images_dir) if f.endswith(('.jpg', '.png'))]) if os.path.exists(images_dir) else 0
        labels_count = len([f for f in os.listdir(labels_dir) if f.endswith('.txt')]) if os.path.exists(labels_dir) else 0

        print(f"   📂 {split}:")
        print(f"      🖼️  Imágenes: {images_count}")
        print(f"      📝 Etiquetas: {labels_count}")

        # Verificar que todas las etiquetas tienen solo clase 0
        if labels_count > 0:
            clases_encontradas = set()
            for label_file in list(os.listdir(labels_dir))[:3]:  # Primeras 3 etiquetas
                label_path = os.path.join(labels_dir, label_file)
                with open(label_path, 'r') as f:
                    for linea in f:
                        clase = linea.strip().split()[0]
                        clases_encontradas.add(clase)
            print(f"      🎯 Clases: {clases_encontradas}")

verificar_dataset_final()

# ============================================================================
# EJECUCIÓN DEL ENTRENAMIENTO
# ============================================================================

print(f"\n🚀 INICIANDO FINE-TUNING...")
print("=" * 60)

start_time = time.time()

try:
    # Iniciar entrenamiento
    results = model.train(**training_config)

    end_time = time.time()
    training_duration = (end_time - start_time) / 60  # En minutos

    print(f"\n✅ FINE-TUNING COMPLETADO!")
    print(f"⏱️  Duración total: {training_duration:.2f} minutos")

    # Mostrar métricas finales si están disponibles
    if hasattr(results, 'results_dict'):
        print(f"📊 MÉTRICAS FINALES:")
        print(f"   📦 mAP50 Bounding Box: {results.results_dict.get('metrics/mAP50(B)', 'N/A')}")
        print(f"   🎭 mAP50 Mask: {results.results_dict.get('metrics/mAP50(M)', 'N/A')}")

except Exception as e:
    print(f"❌ ERROR durante el entrenamiento: {e}")

    # Configuración alternativa más simple si falla
    print(f"\n🔄 INTENTANDO CONFIGURACIÓN ALTERNATIVA...")

    training_config_simple = {
        'data': data_yaml_path,
        'epochs': 25,
        'imgsz': 640,
        'batch': 4,
        'lr0': 0.00001,  # LR aún más bajo
        'device': 0,
        'project': '/content/drive/MyDrive/TFG_Modelo2',
        'name': f'fine_tuned_simple_{int(time.time())}',
    }

    try:
        results = model.train(**training_config_simple)
        end_time = time.time()
        training_duration = (end_time - start_time) / 60
        print(f"✅ ENTRENAMIENTO ALTERNATIVO COMPLETADO")
        print(f"⏱️  Duración: {training_duration:.2f} minutos")
    except Exception as e2:
        print(f"❌ ERROR en configuración alternativa: {e2}")

# ============================================================================
# VERIFICACIÓN DEL MODELO ENTRENADO
# ============================================================================

print(f"\n🔍 VERIFICANDO MODELO ENTRENADO...")

# Buscar el último modelo entrenado
project_dir = '/content/drive/MyDrive/TFG_Modelo2'
latest_run = None
latest_time = 0

if os.path.exists(project_dir):
    for item in os.listdir(project_dir):
        item_path = os.path.join(project_dir, item)
        if os.path.isdir(item_path) and item.startswith('fine_tuned_'):
            mod_time = os.path.getmtime(item_path)
            if mod_time > latest_time:
                latest_time = mod_time
                latest_run = item

if latest_run:
    weights_path = os.path.join(project_dir, latest_run, 'weights', 'best.pt')
    if os.path.exists(weights_path):
        print(f"✅ MODELO GUARDADO EN: {weights_path}")

        # Cargar y validar el modelo
        try:
            trained_model = YOLO(weights_path)
            print("🎯 MODELO CARGADO CORRECTAMENTE PARA VALIDACIÓN")

            # Validación rápida
            print("🧪 REALIZANDO VALIDACIÓN RÁPIDA...")
            metrics = trained_model.val(
                data=data_yaml_path,
                split='valid',  # Usar el conjunto de validación
                conf=0.5,
                iou=0.6
            )

            print(f"📊 RESULTADOS VALIDACIÓN:")
            if hasattr(metrics, 'box_map50'):
                print(f"   📦 mAP50: {metrics.box_map50:.4f}")
            elif hasattr(metrics, 'box') and hasattr(metrics.box, 'map50'):
                print(f"   📦 mAP50: {metrics.box.map50:.4f}")

        except Exception as e:
            print(f"⚠️  No se pudo validar el modelo: {e}")
    else:
        print(f"❌ No se encontraron weights en: {weights_path}")
else:
    print("❌ No se encontró la carpeta del entrenamiento")

print(f"\n🎉 PROCESO COMPLETADO!")

import os
from ultralytics import YOLO
import shutil

# Configuración
model = YOLO('/content/drive/MyDrive/TFG_Modelo2/fine_tuned_combinado_1762027129/weights/best.pt')
videos_dir = "/content/drive/MyDrive/Videos_TFG"
output_dir = "/content/drive/MyDrive/TFG_Modelo2/videos_procesados_fine_tuned"

os.makedirs(output_dir, exist_ok=True)

# Encontrar todos los videos
videos = [f for f in os.listdir(videos_dir) if f.endswith(('.mp4', '.avi', '.mov'))]

print(f"🎯 ENCONTRADOS {len(videos)} VIDEOS")

for video in videos:
    input_path = os.path.join(videos_dir, video)
    output_name = f"segmentado_{video}"
    output_path = os.path.join(output_dir, output_name)

    print(f"\n📹 PROCESANDO: {video}")

    # Procesar video
    results = model.predict(
        source=input_path,
        conf=0.5,
        save=True,
        project=output_dir,
        name=video.replace('.', '_'),  # Nombre de subcarpeta
        exist_ok=True
    )

    # Buscar el resultado
    subcarpeta = os.path.join(output_dir, video.replace('.', '_'))
    if os.path.exists(subcarpeta):
        for archivo in os.listdir(subcarpeta):
            if archivo.endswith(('.mp4', '.avi')):
                # Mover y renombrar
                origen = os.path.join(subcarpeta, archivo)
                shutil.move(origen, output_path)
                print(f"✅ GUARDADO: {output_name}")
                break

print("\n🎉 TODOS LOS VIDEOS PROCESADOS")